#!/bin/bash
cd "`dirname $0`"
set -e

if which npm; then
    npm test
fi

VERSION=`cat package.json|grep \"version\"|cut -d\" -f4`
docker build -t shasoco/shasoco:latest .
docker tag -f shasoco/shasoco:latest shasoco/shasoco:$VERSION
