#!/bin/bash

# Load environment (may fail, we can ignore and see if npm works)
if [ "_$NVM_DIR" != _ ]; then
    . $NVM_DIR/nvm.sh
fi
. setenv

# Exit on failure
set -e

# Run a quick test (fast, better that detecting failure on heavy tests)
npm test

# Start the VM
vagrant up

# Deploy shasoco for faked domain fovea.cc
vagrant ssh --command "echo 127.0.1.1 www.fovea.cc gitlab.fovea.cc directory.fovea.cc | sudo tee -a /etc/hosts"
vagrant ssh --command "/vagrant/build-image"
vagrant ssh --command "/vagrant/shasoco create v0.fovea.cc fovea.cc"

# Test that all services are up and running, and that shasoco report is correct.
vagrant ssh --command "curl -sik https://www.fovea.cc" | grep wp-admin
vagrant ssh --command "curl -sik https://gitlab.fovea.cc" | grep users/sign_in | grep Location
vagrant ssh --command "curl -sik https://directory.fovea.cc/fusiondirectory/" | grep FusionDirectory | grep title
vagrant ssh --command "/vagrant/shasoco ps" | grep v0.fovea.cc | grep UP

# Launch a backup/restore
vagrant ssh --command "/vagrant/shasoco backup v0.fovea.cc 0"
vagrant ssh --command "/vagrant/shasoco restore v0.fovea.cc 0"

echo
echo Shasoco test VM will be destroyed in 30 minutes. Hit CTRL-C to cancel.
echo
sleep 3600
vagrant destroy -f
