#!/bin/bash
#
# shasoco CLI
# (c)2015, fovea.cc
#
# This is a meta-script that will launch the real tool inside its own docker
# container. However this script got its responsibilities too:
#
# - Run the tool at a selected version
# - Remember the selected version
# - Create a data-container to store the data
# - Add a backdoor to inside the shasoco container environment
#

set -e

SHASOCO_PATH=/var/lib/shasoco

# shasoco will run using the same version as last run
# upgrades aren't automatic.
if [ -z $SHASOCO_VERSION ]; then
    mkdir -p ~/.shasoco
    if [ -f ~/.shasoco/version ]; then
        . ~/.shasoco/version
    else
        echo "SHASOCO_VERSION=latest" >> ~/.shasoco/version
    fi
fi

# "shasoco version" will either show or set the version in use
if [ _$1 = _version ]; then
    if [ _$2 = _ ]; then
        echo "Using shasoco version '$SHASOCO_VERSION'"
    else
        SHASOCO_VERSION=$2
        docker pull shasoco/shasoco:$SHASOCO_VERSION
        #docker run --privileged -v $(which docker):/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -v $(readlink -f /var/lib/docker):/var/lib/docker --rm -w /shasoco/compose shasoco/shasoco:$SHASOCO_VERSION docker-compose pull
        echo "SHASOCO_VERSION=$SHASOCO_VERSION" >> ~/.shasoco/version
        echo "Enabled shasoco version '$2'"
    fi
    exit 0
fi

# Create a data container for shasoco's internals:
# this include config files for each projects and backups.
# Data is stored in "/var/lib/shasoco"
if docker ps -a | grep '\bshasocodata\b' > /dev/null; then true; else
    mkdir -p $SHASOCO_PATH
    docker run -v $SHASOCO_PATH:$SHASOCO_PATH --name shasocodata debian:jessie true
fi

# Allow to open a shell inside the shasoco environment
# This is mostly for debuging during development
COMMAND=/shasoco/bin/shasoco.js
if [ _$1 = _shell ]; then
    COMMAND=bash
    EXTRA=-it
    shift
fi

# Run shasoco into its own container, but share our network and docker server.
docker run \
    $EXTRA \
    --net=host \
    --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --volumes-from shasocodata \
    shasoco/shasoco:$SHASOCO_VERSION \
    $COMMAND "$@"

