#!/bin/bash
set -e
mkdir -p ~/.shasoco/domains

if [ -z $SHASOCO_VERSION ]; then
    if [ -f ~/.shasoco/version ]; then
        . ~/.shasoco/version
    else
        echo "SHASOCO_VERSION=latest" >> ~/.shasoco/version
    fi
fi

if [ _$1 = _version ]; then
    if [ _$2 = _ ]; then
        echo "Using shasoco version '$SHASOCO_VERSION'"
    else
        SHASOCO_VERSION=$2
        docker pull jeko/shasoco:$SHASOCO_VERSION
        docker run --privileged -v $(which docker):/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -v $(readlink -f /var/lib/docker):/var/lib/docker --rm -it -w /shasoco/compose jeko/shasoco:$SHASOCO_VERSION docker-compose pull
        echo "SHASOCO_VERSION=$SHASOCO_VERSION" >> ~/.shasoco/version
        echo "Enabled shasoco version '$2'"
    fi
    exit 0
fi

docker run --privileged -v $(which docker):/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -v $(readlink -f /var/lib/docker):/var/lib/docker --rm -it -v "$HOME:/root" -v "$(pwd):$(pwd)" -w "$(pwd)" jeko/shasoco:$SHASOCO_VERSION /shasoco/bin/shasoco.js "$@"
